endroid_data_sanitize:
    entities:
        project:
            class: Endroid\Bundle\DataSanitizeBundle\Entity\Project
            fields: [ 'id', 'name' ]
        user:
            class: Endroid\Bundle\DataSanitizeBundle\Entity\User
            fields: [ 'id', 'name' ]
        task:
            class: Endroid\Bundle\DataSanitizeBundle\Entity\Task
            fields: [ 'id', 'name', 'project', 'user' ]
        tag:
            class: Endroid\Bundle\DataSanitizeBundle\Entity\Tag
            fields: [ 'id', 'name' ]